- README.md
- scripts/helpers.sh
- scripts/toggle.sh
Use bash(1) to parse user-defined Tmux commands. Semicolons in hooks (`@popup-on-open` and `@popup-on-close`) must now be explicitly escaped or quoted.
> refactor: commands parsing

- README.md
- scripts/helpers.sh
- scripts/toggle.sh
1. Add two new hooks: `@popup-before-open` and `@popup-after-close`, which are executed within the caller.
2. Rename `@popup-on-open` to the more intuitive name `@popup-on-init`.
3. Remove the `@popup-on-close` hook, as it cannot handle popup exits. Instead, consider setting the `client-detached` and `pane-exited` hooks in `@popup-on-init`.
> refactor: hooks

- README.md
- scripts/focus.sh
- toggle-popup.tmux
Add `@popup-focus`, primarily used as a workaround of tmux/tmux#3991.
> feat(keybinding): add `@popup-focus` to manually fire focus events

- .prettierignore
- CHANGELOG.md
- README.md
- Tmux commands are parsed by bash(1), thus semicolons in hooks (`@popup-on-open` and `@popup-on-close`) must now be explicitly escaped or quoted ([#1](https://github.com/loichyan/tmux-toggle-popup/pull/1)).
- `@popup-on-open` is renamed to `@popup-on-init` ([#2](https://github.com/loichyan/tmux-toggle-popup/pull/2)).
- `@popup-on-close` is removed, as it cannot handle popup exits. Instead, consider setting the `client-detached` and `pane-exited` hooks in `@popup-on-init` ([#2](https://github.com/loichyan/tmux-toggle-popup/pull/2)).
- Add two new hooks: `@popup-before-open` and `@popup-after-close` ([#2](https://github.com/loichyan/tmux-toggle-popup/pull/2)).
- Add `@popup-focus`, primarily used as a workaround of [tmux/tmux#3](https://github.com/tmux/tmux/issues/3991) …
> release: v0.2.0

- scripts/toggle.sh
As mentioned in <https://github.com/loichyan/tmux-toggle-popup/pull/5#issuecomment-2415237970>, environment overrides are not set properly in opened popups. This is because commands actually start inside a tmux session, which is typically running in a standalone tmux instance, so environment overrides in `display-popup -e KEY=value` are not set in the attached tmux session unless we explicitly forward them to `new-session -e KEY=value`.
> fix: forward environment overrides to popup sessions

- scripts/toggle.sh
Hello again @loichyan,
I just encountered a tiny bug with environment variables with spaces, but this should fix it in my opinion.
In the case for the toggle on the neovim plugin, your suggestion of adding a temporary binding worked out like a charm.
> fix: issue with having environment variables that are with spaces

- toggle-popup.tmux
Fixes #10. Brings the check for the `@popup-autostart` option back, which was unexpectedly removed in [@d95d654f](https://github.com/loichyan/tmux-toggle-popup/commit/d95d654f3eee8f1b9e86ebc000a9718305a442ce).
> fix: respect the user's `@popup-autostart` setting

- README.md
- scripts/focus.sh
- scripts/helpers.sh
- scripts/toggle.sh
- scripts/variables.sh
- tests.sh
- tests/commands-parser.sh
- toggle-popup.tmux
Currently, we use Bash to interpret tmux commands through `eval tmux <commands>`. This method is generally unsafe and may introduce mental overhead due to syntax differences between Bash and tmux (e.g., a session name like `$aaa` may be expanded as a variable in Bash). This PR introduces a new parser for a more robust solution. 
Internally, we use `xargs` to parse arguments into sequences and `printf %q` to escape each one. This allows users to input `;` directly as the command delimiter without worrying about Bash's interpretation. For the precisely supported syntax, please refer to the updated README.
Additionally, this PR adds the missing parse process for the `--on-init`, `--before-open`, and `--after-close` arguments in `@popup-toggle`. @cenk1cenk2, the `tmux_escape(...)` function …
> feat!: improve hooks parsing and escaping

- scripts/helpers.sh
- scripts/toggle.sh
- scripts/variables.sh
- toggle-popup.tmux
tmux 3.5 and 3.5a introduce some changes to the default shell used for executing commands in `display-popup` [^1] [^2] [^3]. Our scripts are written in `sh`, which means if users employ a shell that is incompatible with `sh` syntax, such as `fish`, these commands may not be recognized correctly. This PR ensures tmux uses `/bin/sh` to execute popup commands and also properly propagates the user's `default-shell` option to the popup server, as the aforementioned upstream updates change `$SHELL` to `/bin/sh`.
[^1]: tmux/tmux@f95d055e04f129b015a46deb702081b8b87636ca
[^2]: tmux/tmux@d39dcea30ad2814a70a1f65e43468a78df4df8e5
[^3]: tmux/tmux#4162
> fix: ensure popup commands are interpreted by sh

- README.md
- scripts/toggle.sh
As reported in https://github.com/loichyan/tmux-toggle-popup/pull/14#issuecomment-2423079629, once in the popup, we must promptly revert to the user's default shell to prevent long-running processes from permanently altering it.
> fix: revert to `default-shell` promptly

- scripts/toggle.sh
If a popup is opened twice, the first toggle call may render the subsequent toggle call in another client ineffective, as it clears the popup opened flag.
> fix: do not clear the popup opened flag before detaching

- scripts/really-open.sh
- scripts/toggle.sh
I’m not sure if this will resolve the hanging issue reported in https://github.com/loichyan/tmux-toggle-popup/pull/15#issuecomment-2424160328, but since we do not reattach to the working session at all, it may improve the situation. 
To elaborate further, instead of changing the user's `default-shell`, we put the entire open script in a temporary env variable and call `./really-open.sh` to execute these commands. This approach only requires the user's default shell to support the `exec` command, which I believe most shells do.
> fix: improve workarounds for default shell of popups

- CHANGELOG.md
- cliff.toml
- Use xargs(1) and printf(1) to parse tmux commands ([#8](https://github.com/loichyan/tmux-toggle-popup/pull/8)). This allows users to input `;` directly as the command delimiter without worrying about Bash's interpretation. The new parser may yield results that differ from the previous version, although this is usually not the case.
- We've implemented several improvements to make it easier for other programs to integrate with this plugin ([#5](https://github.com/loichyan/tmux-toggle-popup/pull/5), [#9](https://github.com/loichyan/tmux-toggle-popup/pull/9)). You can now override popup global options on the fly using the newly added arguments for `@popup-toggle`.
- This release also includes some fixes to address the changes in `display-popup` introduced in tmux versions 3.5 and 3.5a …
> chore(release): v0.3.0

- README.md
- scripts/focus.sh
- scripts/helpers.sh
- scripts/really-open.sh
- scripts/toggle.sh
- scripts/variables.sh
- tests/commands-parser.sh
- tests/test-helpers.sh
If the user defines many different popup key bindings, it is often the case that forcing opened popups to close or popup-in-popups is not the desired behavior to deal with nested toggle calls. This PR introduces a new toggle mode, `switch`, which allows for quick switching between open popups. Specifically, in the `switch` toggle mode, when a different popup is toggled, `@popup-toggle` will reuse the currently opened popup window and switch to the newly specified one.
BREAKING CHANGE: 
1. `@popup-toggle --force` is replaced with `--toggle-mode=force-close`. 
2. tmux variable `#{@popup_name}` in `@popup-id-format` is replaced with `{popup_name}`.
> feat!: support switch popups when toggled

- .prettierrc
- CHANGELOG.md
- README.md
- scripts/helpers.sh
- scripts/really_open.sh
- scripts/toggle.sh
- toggle-popup.tmux
Remove the obsolete syntax for hook options deprecated in #8, specifically the use of line breaks as command delimiters. Also, format some comments and documents.
> docs: update usages and format documents

- CHANGELOG.md
- README.md
- scripts/toggle.sh
- toggle-popup.tmux
Add a new argument, `@popup-toggle --id <id>`, useful for creating a globally shared popup. This can also be done by using `@popup-toggle --id-format <id>`, but it breaks the consistency of `id-format` across different popups, which is crucial for the `switch` toggle mode function.
> feat: add argument `@popup-toggle --id <id>`

- CHANGELOG.md
Ensure bullet list items are not terminated with punctuation unless they are complete sentences.
> style: remove peroids after verb phrases

- CHANGELOG.md
- scripts/helpers.sh
- scripts/toggle.sh
Replace special characters in the popup ID to ensure `@popup-toggle` does not fail if the current directory contains special chars: tmux replaces special chars like `.` or `:` in a session name, it's necessary to perform the same behavior so as to get a proper name.
> fix: replace special chars in popup ID

- CHANGELOG.md
- scripts/toggle.sh
Forward working directory to popup sessions to ensure `@popup-toggle -d <dir>` functions properly in switch mode.
> fix: forward working directory to popup sessions

- CHANGELOG.md
- scripts/toggle.sh
Forward current popup's ID format in switch mode to ensure the intended popup is opened when switching.
> fix: forward current ID format in switch mode

- CHANGELOG.md
- toggle-popup.tmux
- Add a new argument, `@popup-toggle --id <id>`, to directly set the ID of a popup, useful for creating globally shared popups ([#27])
- Replace special characters in the popup ID to ensure `@popup-toggle` does not fail if the current directory contains dots (`.`) or colons (`:`) ([#29])
- Forward working directory to popup sessions to ensure `@popup-toggle -d <dir>` functions properly in switch mode ([#30])
- Forward current popup's ID format in switch mode to ensure the intended popup is opened when switching ([#31])
[#27]: https://github.com/loichyan/tmux-toggle-popup/pull/27
[#29]: https://github.com/loichyan/tmux-toggle-popup/pull/29
[#30]: https://github.com/loichyan/tmux-toggle-popup/pull/30
[#31]: https://github.com/loichyan/tmux-toggle-popup/pull/31
> chore: release v0.4.1

- CHANGELOG.md
- src/eval.sh
- src/toggle.sh
Temporarily change `default-shell` to `/bin/sh` to execute the shell script that launches popup sessions:
1. It addresses the issue described in #14.
2. It should not bring the regressions reported in #15.
3. It also provides a performance boost when opening a popup, since the user shell may take some time to customize before it's ready to run commands.
On my laptop, this PR reduces the latency by ~40% when opening popups.
Before:
```console
$ hyperfine --shell=/bin/sh --warmup 3 "./src/toggle.sh -E --toggle-mode=force-open --on-init='detach'"
Benchmark 1: ./src/toggle.sh -E --toggle-mode=force-open --on-init='detach'
Time (mean ± σ):      48.7 ms ±   2.0 ms    [User: 7.2 ms, System: 7.7 ms]
Range (min … max):    44.4 ms …  55.0 ms    61 runs
```
After:
```console
$ hyperfine …
```
> perf: use `/bin/sh` to launch popup sessions

- CHANGELOG.md
- README.md
- src/focus.sh
- src/helpers.sh
- src/toggle.sh
- tests/command_parser_tests.sh
- toggle-popup.tmux
Support using `{popup_caller_path}` and `{popup_caller_pane_path}` to open popups. These two variables are equivalent (though not necessarily identical) to `#{session_path}` and `#{pane_current_path}`. While the difference can be quite subtle, consider the following procedure:
```sh
declare dir
test() {
name=${1}
tmux run "#{@popup-toggle} -Ed'$dir' --toggle-mode=force-open --name=${name}_1 bash" &
sleep 2
tmux -Lpopup send -l "echo -e '\x1b[1;31mtest $name with directory=$dir\x1b[0m'"
tmux -Lpopup send Enter
tmux -Lpopup send -l 'echo -e "\x1b[1;31m>>> PWD=$PWD\x1b[0m"'
tmux -Lpopup send Enter
tmux -Lpopup send -l 'cd $(mktemp -d)'
tmux -Lpopup send Enter
tmux -Lpopup send -l 'echo -e "\x1b[1;31m>>> PWD=$PWD\x1b[0m"'
tmux -Lpopup send Enter
tmux -Lpopup send -l 'echo -e "\x1b[1;31m>>> …
```
> feat: support opening popups with the caller path

- .github/workflows/cicd.yml
- CHANGELOG.md
- src/helpers.sh
- src/toggle.sh
Currently, if `@popup-on-init` is set to empty, the default value is used as a fallback. This makes it impossible to disable that hook. After this PR, you can set it to `nop` to disable it explicitly.
> feat: support disabling a hook explicitly

- CHANGELOG.md
- src/toggle.sh
- src/toggle_tests/open_nested_popup.stdout
- src/toggle_tests/open_nested_with_toggle_key.stdout
- src/toggle_tests/open_popup.stdout
- src/toggle_tests/open_with_toggle_key.stdout
- toggle-popup.tmux
Generally, adding tmux calls will also increase the latency when opening a popup window, as shown below:
Before this PR:
```console
$ hyperfine --shell=/bin/sh --warmup=3 "./src/toggle.sh -E --before-open='run true' --on-init='detach' --after-close='run true'"
Benchmark 1: ./src/toggle.sh -E --before-open='run true' --on-init='detach' --after-close='run true'
Time (mean ± σ):      64.1 ms ±  17.8 ms    [User: 17.1 ms, System: 24.2 ms]
Range (min … max):    38.5 ms …  94.8 ms    70 runs
```
After:
```console
$ hyperfine --shell=/bin/sh --warmup=3 "./src/toggle.sh -E --before-open='run true' --on-init='detach' --after-close='run true'"
Benchmark 1: ./src/toggle.sh -E --before-open='run true' --on-init='detach' --after-close='run true'
Time (mean ± σ):      39.7 ms ±   2.9 ms    [User: 11.7 …
```
> perf: open popup window and run hooks in a single execution

- src/helpers.sh
- src/helpers_tests.sh
- src/toggle_tests/open_nested_with_toggle_key.stdout
- src/toggle_tests/open_with_toggle_key.stdout
- src/toggle_tests/tmux
If a variable is `-n` or `-e`, it will be recognized as arguments for echo, which can lead to bugs that are extremely difficult to discover.
> fix: prefer printf to show variable values

- CHANGELOG.md
- toggle-popup.tmux
This release resolves a long-standing issue with `@popup-toggle` on macOS's ancient built-in Bash ([#44]). Thanks to [u/Beautiful_Baseball76] for the feedback , which also motivated me to add a number of integration tests, although many are powered by some "dark" Bash magic =.=
- Distribute this plugin to nixpkgs ([#42], [NixOS/nixpkgs#428294], thanks [@szaffarano])
- Support specifying the socket path for the popup server ([#43])
- The `before-open` and `after-close` hooks are called in the same execution that opens the popup window. This should rarely have side effects ([#46])
- Support macOS's ancient built-in Bash ([#44])
- Forward all arguments when setting specified toggle keys ([#45])
[#42]: https://github.com/loichyan/tmux-toggle-popup/pull/42
[#43]: …
> chore: release v0.4.3

- CHANGELOG.md
- README.md
- toggle-popup.tmux
This release doesn't include major updates but fixes a bug that occurred when using multiple popups specified with `--id`.
- Resolve name conflicts when using `--id` ([#52])
[#52]: https://github.com/loichyan/tmux-toggle-popup/pull/52
> chore: release v0.4.4
